Update dev.yaml
Only Keep Prod and change to event trigger

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -1,16 +1,19 @@
 name: CI/CD Pipeline for Industrial IoT Application
 
 on:
-  pull_request:
-    branches:
-      - dev
-      - uat
-      - prod
+  workflow_dispatch:  # Manually trigger the workflow
+
+#on:
+#  pull_request:
+#    branches:
+#      - dev
+#      - uat
+#      - prod
 
 jobs:
-  dev:
+  prod:
     runs-on: ubuntu-latest
-    environment: dev 
+    environment: prod
     
     steps:
     - name: Checkout
@@ -38,55 +41,55 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
+    # - name: Setup Terraform
+    #   uses: hashicorp/setup-terraform@v2
          
-    - name: Terraform fmt
-      run: terraform fmt -check
+    # - name: Terraform fmt
+    #   run: terraform fmt -check
 
-    - name: Terraform Init
-      run: terraform init
+    # - name: Terraform Init
+    #   run: terraform init
 
-    - name: Terraform Validate
-      run: terraform validate
+    # - name: Terraform Validate
+    #   run: terraform validate
 
-    - name: Start LocalStack
-      uses: LocalStack/setup-localstack@v0.2.2
-      with:
-        image-tag: 'latest'
-        install-awslocal: 'true'
+    # - name: Start LocalStack
+    #   uses: LocalStack/setup-localstack@v0.2.2
+    #   with:
+    #     image-tag: 'latest'
+    #     install-awslocal: 'true'
           
 
-    - name: Wait for LocalStack to be ready
-      run: |
-            echo "Waiting for LocalStack to be ready..."
-            while ! curl -s http://localhost:4566/_localstack/ready; do
-              echo "LocalStack not ready yet, retrying in 5 seconds..."
-              sleep 5
-            done
-            echo "LocalStack is ready!" 
+    # - name: Wait for LocalStack to be ready
+    #   run: |
+    #         echo "Waiting for LocalStack to be ready..."
+    #         while ! curl -s http://localhost:4566/_localstack/ready; do
+    #           echo "LocalStack not ready yet, retrying in 5 seconds..."
+    #           sleep 5
+    #         done
+    #         echo "LocalStack is ready!" 
 
-    - name: Terraform Plan
-      run: terraform plan
+    # - name: Terraform Plan
+    #   run: terraform plan
 
-    - name: Reset LocalStack state
-      run: |
-        curl -X POST http://localhost:4566/_localstack/reset
+    # - name: Reset LocalStack state
+    #   run: |
+    #     curl -X POST http://localhost:4566/_localstack/reset
 
-    - name: Terraform State List
-      run: terraform state list
+    # - name: Terraform State List
+    #   run: terraform state list
 
-    - name: Terraform Destory 
-      run: terraform destroy -auto-approve
+    # - name: Terraform Destory 
+    #   run: terraform destroy -auto-approve
 
-    - name: Run Terraform Apply (LocalStack)
-      env:
-           USE_LOCALSTACK: "true"
-      run: |
-          terraform apply -target=module.lab02 -auto-approve
+    # - name: Run Terraform Apply (LocalStack)
+    #   env:
+    #        USE_LOCALSTACK: "true"
+    #   run: |
+    #       terraform apply -target=module.lab02 -auto-approve
 
-    - name: Terraform Destroy
-      run: terraform destroy -auto-approve
+    # - name: Terraform Destroy
+    #   run: terraform destroy -auto-approve
 
   #  - name: Terraform State
   #    run: terraform state rm module.lab01.aws_ses_email_identity.delivery_alert_email
@@ -100,116 +103,116 @@ jobs:
   #  - name: Destroy Source Email
   #    run: terraform destroy -target=module.lab01.aws_ses_email_identity.source_alert_email
 
-  uat:
-    runs-on: ubuntu-latest
-    needs: dev
-    if: github.base_ref == 'uat' || github.base_ref == 'prod'
-    environment: uat 
+  # uat:
+  #   runs-on: ubuntu-latest
+  #   needs: dev
+  #   if: github.base_ref == 'uat' || github.base_ref == 'prod'
+  #   environment: uat 
 
-    steps:
-      - name: Deploy
-        run: echo "deploy to uat"
+  #   steps:
+  #     - name: Deploy
+  #       run: echo "deploy to uat"
 
-      - name: Checkout
-        uses: actions/checkout@v3
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Set Up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: 'npm'
+  #     - name: Set Up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         cache: 'npm'
 
-      - name: Install Dependencies
-        run: npm install
+  #     - name: Install Dependencies
+  #       run: npm install
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ap-southeast-1
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ap-southeast-1
 
-      - name: Install Snyk
-        run: npm install -g snyk
+    - name: Install Snyk
+      run: npm install -g snyk
 
-      - name: Authenticate Snyk
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        run: snyk auth $SNYK_TOKEN
+    - name: Authenticate Snyk
+      env:
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      run: snyk auth $SNYK_TOKEN
 
-      - name: Run Snyk code test
-        run: snyk code test
+    - name: Run Snyk code test
+      run: snyk code test
 
-      - name: Run Snyk ignore 
-        run: snyk ignore --id=SNYK-CC-AWS-415
+    - name: Run Snyk ignore 
+      run: snyk ignore --id=SNYK-CC-AWS-415
 
-      - name: Run Snyk iac test
-        run: snyk iac test
+    - name: Run Snyk iac test
+      run: snyk iac test
 
-      - name: Run Snyk test
-        run: snyk test     
+    - name: Run Snyk test
+      run: snyk test     
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
 
-      - name: Terraform Format
-        run: terraform fmt -recursive
+    - name: Terraform Format
+      run: terraform fmt -recursive
 
-      - name: Terraform fmt
-        run: terraform fmt -check
+    - name: Terraform fmt
+      run: terraform fmt -check
 
-      - name: Terraform Init
-        run: terraform init
+    - name: Terraform Init
+      run: terraform init
 
-      - name: Terraform Validate
-        run: terraform validate
+    - name: Terraform Validate
+      run: terraform validate
 
-      - name: Terraform Plan
-        run: terraform plan
+    - name: Terraform Plan
+      run: terraform plan
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
+    - name: Terraform Apply
+      run: terraform apply -auto-approve
 
-  prod:
-    runs-on: ubuntu-latest
-    needs: uat
-    if: github.base_ref == 'prod'
-    environment: prod 
+  # prod:
+  #   runs-on: ubuntu-latest
+  #   needs: uat
+  #   if: github.base_ref == 'prod'
+  #   environment: prod 
 
-    steps:
-      - name: Deploy
-        run: echo "deploy to prod"
+  #   steps:
+  #     - name: Deploy
+  #       run: echo "deploy to prod"
 
-      - name: Checkout
-        uses: actions/checkout@v3
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Set Up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: 'npm'
+  #     - name: Set Up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         cache: 'npm'
 
-      - name: Install Dependencies
-        run: npm install
+  #     - name: Install Dependencies
+  #       run: npm install
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ap-southeast-1
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ap-southeast-1
     
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
 
-      - name: Terraform Init
-        run: terraform init
+  #     - name: Terraform Init
+  #       run: terraform init
 
-      - name: Terraform Plan
-        run: terraform plan
+  #     - name: Terraform Plan
+  #       run: terraform plan
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
+  #     - name: Terraform Apply
+  #       run: terraform apply -auto-approve
       
 
   #   env:
